# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 4
#      matrix:
#        python-version: [3.8]

    steps:
    # git에서 설정한 비공개 변수
    - name: checkout source code
      uses: actions/checkout@v3
    ###################################################
    - name: Retrieve version
      id: img-ver
      run: |
        echo "TAG_NAME=$(cat version)" >> $GITHUB_OUTPUT
    - name: build
      run: docker build -t seongdong/nginx-test:${{ steps.img-ver.outputs.TAG_NAME  }} .

    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PW }}

    - name: Push to Docker
      run: docker push seongdong/nginx-test:${{ steps.img-ver.outputs.TAG_NAME  }}

    ### pre cd
    - name: Setup Kustomize
      #      uses: imranismail/setup-kustomize@v1
      uses: yokawasa/action-setup-kube-tools@v0.9.2
      with:
        kustomize: "3.7.0"

    - name: Checkout kustomize repository
      uses: actions/checkout@v3
      with:
        repository: "Seong-dong/cicd-test-cd"
        ref: main
        token: ${{ secrets.ACTION_TOKEN }}
        path: cicd-test-cd

    - name: Update Kubernetes resources
      run: |
        cd cicd-test-cd/overlays/dev/
        kustomize edit set image \seongdong/nginx-test:\${{ steps.img-ver.outputs.TAG_NAME }}
        cat kustomization.yaml

    - name: Commit files
      run: |
        cd cicd-test-cd
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git commit -am "Update image tag"
        git push -u origin main
