# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    # git에서 설정한 비공개 변수
    - name: checkout source code
      uses: actions/checkout@v3
    ###################################################
    - name: get-version
      id: image-version
      run: echo "version=$(cat version)" >> $GITHUB_OUTPUT
    - name: build
      id: image-version
      run: docker build -t seongdong/nginx-test:${{ step.image-version.outputs.version  }} .
        #run: docker build -t seongdong/nginx-test:$(cat version) .

    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PW }}

    - name: Push to Docker
      run: docker push seongdong/nginx-test:${{ step.image-version.outputs.version  }}
        #run: docker push seongdong/nginx-test:$(cat version)
